# AskPermission: true/false - Should players be asked for permission when someone tries to teleport to them?
AskPermission: true
# TeleportDelay: <number> - How much to wait, in seconds, until teleportation. TeleportDelay: 0 is basically no delay.
TeleportDelay: 5
# TeleportRequestTimeout: <number> - How long, in seconds, until a request will expire? 0 means never expire.
TeleportRequestTimeout: 30
# CancelTeleportWhenAttacked: true/false - Cancel teleportation when a player is attacked by mobs/players. Requires TeleportDelay to be 1 or higher.
CancelTeleportWhenAttacked: true
#TeleportOffset:
#  x: 0  # how far to teleport from the target in the x-axel  # negative values are allowed
#  y: 0  # how far to teleport from the target in the y-axel  # negative values are allowed
#  z: 0  # how far to teleport from the target in the z-axel  # negative values are allowed
TeleportOffset:
  x: 0
  y: 0
  z: 0